Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'api/**/*'
    - 'web/**/*'

Metrics:
  Exclude:
    - 'api/**/*'
    - 'web/**/*'