services:
  db:
    image: postgres
    container_name: myPG
    environment:
      - POSTGRES_USER=rebase_labs
      - POSTGRES_PASSWORD=labs_password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:  
    image: ruby
    container_name: myApi
    volumes:
      - .:/app
    working_dir: /app
    environment:
      REDIS_URL: redis://myRedis:6379
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true 
    command: bash -c "bundle install --without test && ruby api/app.rb"
  
  web:
    image: ruby
    container_name: myWeb
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true
    stdin_open: true 
    command: bash -c "bundle install --without test && ruby web/app.rb"

  apitest:
    image: ruby
    container_name: apiTest
    volumes:
      - .:/app
    working_dir: /app/api
    depends_on:
      - api
    command: bash -c "bundle install && bundle exec rspec"

  webtest:
    image: ruby
    container_name: webTest
    volumes:
      - .:/app
    working_dir: /app/web
    depends_on:
      - web
    command: bash -c "bundle install && bundle exec rspec"

  redis:
    image: redis
    container_name: myRedis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - .:/data

  sidekiq:
    image: ruby
    container_name: mySidekiq
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_URL=redis://myRedis:6379/0
    depends_on:
      - api
      - redis
    command: bash -c "bundle install --without test && bundle exec sidekiq -r ./api/src/import_job.rb"

volumes:
  db_data: