services:
  db:
    image: postgres
    container_name: mypg
    environment:
      - POSTGRES_USER=rebase_labs
      - POSTGRES_PASSWORD=labs_password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile.api
    container_name: myapi
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true 
    command: bash -c "bundle install --without test && ruby api/app.rb"
  
  web:
    image: ruby
    container_name: myweb
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true
    stdin_open: true 
    command: bash -c "bundle install --without test && ruby web/app.rb"

  apitest:
    image: ruby
    container_name: apitest
    volumes:
      - .:/app
    working_dir: /app/api
    depends_on:
      - api
    command: bash -c "bundle install && bundle exec rspec"

  webtest:
    image: ruby
    container_name: webtest
    volumes:
      - .:/app
    working_dir: /app/web
    depends_on:
      - web
    command: bash -c "bundle install && bundle exec rspec"

volumes:
  db_data: